### ISSUE TITLE
nVidia Shield: Storage Permission toggle disappears (too quickly to toggle ALLOW)

### ISSUE THREAD

**Issue by splaquet** [StefanIlchev/ElementumService#5]
As others have mentioned, thank you so much for your generous work!

I've tried installing various releases, but keep having the same issue.  I try and open Elementum, then have a pop-up that says:
`adb shell appops set --uid service.elementum.android MANAGE_EXTERNAL_STORAGE allow`

there's an OK button, but that's about it.

whenever trying to open Elementum, it's still giving me the "still warming up" notice.

when i go into the app permissions, i'll see a permissions box QUICKLY... before it then vanishes.  i've tried quickly pressing down, but cannot seem to get onto the spot to toggle the ALLOW permissions.

any suggestions?

![ElementumService_notice](https://user-images.githubusercontent.com/6146508/149635906-dee286c5-166d-4ce5-a404-d2f65353352a.jpg)

**Comment by splaquet** [comment]
oh... geeezus.  MY APOLOGIES!  ...i'm THAT fool.  the one who failed to read your readme 🙁   LOL

**Comment by StefanIlchev** [comment]
No problem, I was just about to direct you to the readme :)

**Comment by ChristianCiach** [comment]
@splaquet As I understand it, Android TV is actually missing the dialog to manage the MANAGE_EXTERNAL_STORAGE permission via the UI (or maybe nvidia has removed the dialog).

**Comment by StefanIlchev** [comment]
@splaquet if you're talking about your device's permissions manager UI then I don't know and it sounds like a bug. It shouldn't appear at all as I don't use the WRITE_EXTERNAL_STORAGE on Android 11 and up because it [does nothing](https://developer.android.com/about/versions/11/privacy/storage#permissions-target-11). I use MANAGE_EXTERNAL_STORAGE which doesn't show up in permissions manager but has its own UI that looks like [this](https://i.stack.imgur.com/zdiQpl.png) on phones and as @ChristianCiach wrote is missing on TVs. When I looked into why this is I found [this issue](https://issuetracker.google.com/issues/71327396?pli=1#comment5) with a "Won't Fix (Obsolete)" status and linked it in the [readme](https://github.com/StefanIlchev/ElementumService#install).

My guess is that your device's permissions manager shows all of the app's declared permissions for a bit for some reason even ones whose max Android version is below the device's and even if you were able to grant it from there it'll do nothing.

Yes, running in the background is a nice side effect of this setup. I've elaborated on this a bit [here](https://github.com/elgatito/plugin.video.elementum/issues/669#issuecomment-1013906496).

**Comment by splaquet** [comment]
Looks like you figured out the approval toggle disappearance 😊 

Nice work!
