### ISSUE TITLE
Slowness on external disk

### ISSUE THREAD

**Issue by iz8mbw** [StefanIlchev/ElementumService#7]
Hello.
I'm using Elementum on Nvidia Shield TV.
Since the Nvidia Shield TV has only 16GB of internal disk space in the past I extended the internal space with a 300GB SSD disk.
The SSD disk is very fast and connected to USB 3 of the Nvidia Shield TV.

Well, before the upgrade to Android 10 all worked fine and fast, I was able to download torrent with Elementum also at 50 MB/sec on that SSD disk and play in the same file in the same time (in Elementum I set to use disk to cache, not the RAM).

Well, now that the Shield is Android 10 I'm force to use ElementumService, OK it works also to copy torrent file into my internal disk (that is this SSD disk) but during downloading and playing a 2160p (4K) movie Kodi skip lots of frame and the playback is not smooth.

For test I have switched the torrent cache in Elementum from disk to memory (RAM) and the issue disappear.
So it seems some slowness to write and read movies (torrent) from disk. Don't know if can depends of ElementumService or it depends of the new Android 10 on the Shield.

On my Nvidia Shield TV I have another external disk (on the other USB port), this is another fast NVME memory.
Well, in Elementum I select this other NVME disk for caching torrent and Elementum accept the path but during a torrent download it was not able to write the file so I suspect that Elementum via ElementumService doesn't have permission to write on this NVME memory.

Well, how can I give to ElementumService the permission also on that other NVME memory?

Thanks.

**Comment by StefanIlchev** [comment]
I doubt it's caused by ElementumService. The app is just a hollow wrapper that requests necessary permissions before starting Elementum's executable and then waits for it to finish before finishing itself. Apart from the initial permissions request there's no other overhead. If you're willing to uninstall Kodi you can try installing one of those modified versions that've had their target Android version lowered and can start Elementum to see if it'll work differently.

I assume your other disk doesn't extend Android's storage but is added as removable storage. In that case it'll probably be read only for third party apps except for the folder "<YOUR-DRIVE>/Android/data/<APP-ID>". What I find odd is that you get so far with a non-writable location selected. Whenever I change the path Elementum checks if it has permission to write and opens the settings dialog again if it doesn't. You can try changing the location to "<YOUR-DRIVE>/Android/data/<APP-ID>" somehow and see if it works there but the picker might not work. Is there even an Android folder on your drive?
